### ISSUE TITLE
Crash when attempting to enable KP module

### ISSUE THREAD

**Issue by rainbowskydancer** [blish-hud/KillProof-Module#20]
I just downloaded the new one like 45 minutes ago. Previous one was functioning normally.

```
System.MissingMethodException: Method not found: 'Blish_HUD.Settings.SettingCollection Blish_HUD.Settings.SettingCollection.AddSubCollection(System.String, Boolean, Boolean)'.
   at KillProofModule.KillProofModule.DefineSettings(SettingCollection settings)
   at Blish_HUD.Modules.Module.DoInitialize() in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\Modules\Module.cs:line 86
   at Blish_HUD.Modules.ModuleManager.Enable() in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\Modules\ModuleManager.cs:line 79
   at Blish_HUD.Modules.ModuleManager.set_Enabled(Boolean value) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\Modules\ModuleManager.cs:line 34
   at Blish_HUD.Settings.UI.SingleModuleSettingsUIBuilder.<>c__DisplayClass0_0.<BuildSingleModuleSettings>b__0(Object <p0>, MouseEventArgs <p1>) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\Settings\UI\SingleModuleSettingsUIBuilder.cs:line 121
   at Blish_HUD.Controls.Control.OnLeftMouseButtonReleased(MouseEventArgs e) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\Controls\Control.cs:line 161
   at Blish_HUD.Controls.Control.TriggerMouseInput(MouseEventType mouseEventType, MouseState ms) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\Controls\Control.cs:line 677
   at Blish_HUD.Controls.Container.TriggerMouseInput(MouseEventType mouseEventType, MouseState ms) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\Controls\Container.cs:line 178
   at Blish_HUD.Controls.Container.TriggerMouseInput(MouseEventType mouseEventType, MouseState ms) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\Controls\Container.cs:line 178
   at Blish_HUD.Controls.Container.TriggerMouseInput(MouseEventType mouseEventType, MouseState ms) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\Controls\Container.cs:line 178
   at Blish_HUD.Controls.Container.TriggerMouseInput(MouseEventType mouseEventType, MouseState ms) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\Controls\Container.cs:line 178
   at Blish_HUD.Controls.Container.TriggerMouseInput(MouseEventType mouseEventType, MouseState ms) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\Controls\Container.cs:line 178
   at Blish_HUD.Input.MouseHandler.Update() in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\Input\Mouse\MouseHandler.cs:line 99
   at Blish_HUD.InputService.Update(GameTime gameTime) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\InputService.cs:line 58
   at Blish_HUD.BlishHud.Update(GameTime gameTime) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\BlishHud.cs:line 118
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.TickOnIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Blish_HUD.Program.Main(String[] args) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\Program.cs:line 60
```

**Comment by agaertner** [comment]
The latest killproof module is for an yet to be released BlishHUD version,

**Comment by rainbowskydancer** [comment]
Ooh, OK, thanks
